### ISSUE TITLE
Android : This device cannot use the camera to read card numbers.

### ISSUE THREAD

**Issue by muraliandroid** [auchenberg/cardio#11]
I am using Eclipse for my Android project. To use card.io. Android SDK I did the following steps.
Step 1: Downloaded latest  card.io. Android SDK version 5.0.0 from (https://github.com/card-io/card.io-Android-SDK ) and extracted the .aar file .
Step 2: In the extracted folder I got "classes.jar" and renamed it to "cardio.jar"
Step 3: Created a project in Eclipse and used the "cardio.jar" file under libs folder of Eclipse project.
Step 4: Added necessary permissions in AndroidManifest file.

```
<uses-permission android:name="android.permission.CAMERA" />
<uses-permission android:name="android.permission.VIBRATE" />

<uses-feature
    android:name="android.hardware.camera"
    android:required="false" />

<uses-feature
    android:name="android.hardware.camera.autofocus"
    android:required="false" />

<application
    android:allowBackup="true"
    android:icon="@drawable/ic_launcher"
    android:label="@string/app_name"
    android:theme="@style/AppTheme" >

    <activity
        android:name=".CreditCardScanner"
        android:label="@string/app_name" >
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
    </activity>

    <activity
        android:name="io.card.payment.CardIOActivity"
        android:configChanges="keyboardHidden|orientation"
        android:hardwareAccelerated="true" />

    <activity
        android:name="io.card.payment.DataEntryActivity"
        android:screenOrientation="portrait" />

</application> 
```

Step 5: Run the application I got following exception in Log cat:

```
   Failed to load native library: Couldn't load cardioDecider from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.ex.creditcardscanner-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.ex.creditcardscanner-1, /vendor/lib, /system/lib]]]: findLibrary returned null

  ERROR_NO_DEVICE_SUPPORT: This device cannot use the camera to read card numbers.
```

Please let me know why I got the error and what is the wrong I did in my steps? 
Is jar file creation process (step 2) right?
How to use car.io Android project in Eclipse?

I have tested my code in Samsung S4, Moto E and Samsung S3.
If you need full error log of the application please mail me to  murali6060.android@gmail.com
Please help me.

**Comment by Tenzer** [comment]
Hi
I think you got the hold of the wrong project, try instead to have a look here: https://github.com/card-io/card.io-Android-SDK as this project isn't related to Android app development :)

**Comment by muraliandroid** [comment]
Hi
I got the sample application from https://github.com/card-io/card.io-Android-SDK  and please let me know how to use "card.io-5.0.0.aar" library in Eclipse? I have downloaded the code and extracted folder I got "classes.jar" and renamed it to "cardio.jar", Is my method correct?

**Comment by Tenzer** [comment]
Dude, you created this issue on the wrong GitHub project. This project is not at all related to the problem you are having. Please go to https://github.com/card-io/card.io-Android-SDK/issues and create it again, then you should get a hold of people who can help you out :)
